
- name: Configure Systems for Ansible and Terminal Use
  hosts: all
  roles:
    - { role: system-setup, tags: ['system-setup'] }
    - { role: user-setup, tags: ['user-setup'] }
    - { role: acl-permissions, tags: ['acl'] }
  tags:
    - setup

# Sample Server Setup Configuration
# - name: Configure Node.js Servers
#   hosts: all
#   roles:
#     - { role: node-server }
#   tags:
#     - node
#
# - name: Configure Apache
#   hosts: all
#   roles:
#     - { role: apache-server }
#   tags:
#     - apache
#
# - name: Configure Nginx
#   hosts: all
#   roles:
#     - { role: nginx-server }
#   tags:
#     - nginx
#
# - name: Configure Capistrano
#   hosts: all
#   roles:
#     - { role: capistrano-deploy }
#   tags:
#     - cap
