

- include: utils/vpc_info.yml
  tags:
    - ec2_include

- name: Create EC2 Instances
  environment: "{{ aws.env }}"
  ec2:
    key_name: "{{ item.value.key }}"
    instance_type: "{{ item.value.type }}"
    image: "{{ item.value.image }}"
    group: "{{ item.value.group }}"
    vpc_subnet_id: "{{ item.value.vpc_subnet_id }}"
    assign_public_ip: "{{ item.value.assign_publick_ip }}"
    instance_tags: "{{ item.value.tags }}"
    count_tag: "{{ item.value.tags }}"
    volumes: "{{ item.value.volumes }}"
    termination_protection: yes
    exact_count: 1
  register: ec2_results
  with_dict: "{{ ec2_instances }}"
