
# - name: Create Site dirs if they don't exist
#   file:
#     path={{item}}
#     state=directory
#     mode=0770
#   with_items:
#     - "{{app.path}}"
#     - "{{app.path}}/site"
#     - "{{app.log}}"
#
# - name: Setup Site Apache Configs
#   become: yes
#   template:
#     src={{item.src}}
#     dest={{item.dest}}
#   with_items:
#     - { src: 'app.conf', dest: '/etc/apache2/sites-available/{{ app.name }}.conf'}
#
# - name: Enable Sites
#   become: yes
#   file:
#     src={{item.src}}
#     dest={{item.dest}}
#     state=link
#   with_items:
#     - { src: '/etc/apache2/sites-available/{{ app.name }}.conf', dest: '/etc/apache2/sites-enabled/{{ app.name }}.conf'}
#   notify: reload apache2
#
# - name: Checkout Site
#   git:
#     repo={{ app.repo }}
#     dest={{ app.path }}/site
#     accept_hostkey=yes
#     version="{{ app.version }}"
