
- name: Install Required Packages
  become: yes
  apt: pkg={{ item }} state=present
  with_items:
    - acl

- name: Set Access Control Lists
  become: yes
  acl:
    state=present
    name={{ item.dir }}
    etype={{ item.etype }}
    entity={{ item.entity }}
    permissions={{ item.perms }}
  with_items: "{{ acl.permissions }}"

- name: Set Default Access Control Lists 
  become: yes
  acl:
    default=yes
    state=present
    name={{ item.dir }}
    etype={{ item.etype }}
    entity={{ item.entity }}
    permissions={{ item.perms }}
  with_items: "{{ acl.permissions }}"
